name: Deploy React to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Lint Validation"]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22" # Atualizado para a versão 22 do Node.js

      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-cache-node-modules-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist/."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Deploy
        uses: actions/deploy-pages@v4
