name: Lint Validation

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-lint-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-lint-cache-node-modules-
            ${{ runner.os }}-lint-

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Upload Node modules cache
        uses: actions/upload-artifact@v3
        with:
          name: node-modules-cache
          path: ~/.npm
