name: Lint Validation

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Super Linter with Custom ESLint Config
        uses: github/super-linter@v5
        env:
          RUN_LOCAL: true
        with:
          args: --enabled linters=eslint --install-deps=false
          ESLINT_CONFIG_FILE: eslint.config.js
